{% set version = "0.1.5" %}

package:
  name: ipycache
  version: {{ version }}

source:
#  - url: https://pypi.python.org/packages/source/i/ipycache/ipycache-{{ version }}.zip
#    md5: c78c6094ffab45b0e33c2f556705fa11
#    fn: ipycache-{{ version }}.zip
#    folder: .
  git_url: https://github.com/rossant/ipycache/
#    folder: master

build:
  number: 0
  script: 
    - cp {{ environ['RECIPE_DIR'] }}/LICENSE.md {{ environ['SRC_DIR'] }} 
    #- python setup.py install --single-version-externally-managed --record=record.txt
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    #- setuptools

  run:
    - python
    - ipython

test:
  source_files:
    - ipynb_runner.py
    - examples
    - test_*
  commands:
    #- cd master
    - nosetests 
    - python ipynb_runner.py -v -s examples/example.ipynb  # [not win]
    - python ipynb_runner.py -v -s examples/example_outputs.ipynb  # [not win]
  
  requires:
    - nose
    - numpy
    - matplotlib-base
    - ipython
    - nbformat
    - ipykernel

about:
  home: http://packages.python.org/ipycache
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: 'Defines a %%cache cell magic in the IPython notebook to cache results of long-lasting computations in a persistentpickle file.'
  
extra:
  recipe-maintainers:
    - jochym
