travis:
  secure:
    BINSTAR_TOKEN: vNiRXU2J6NFlhcq2ds0eZOUxHIailodgcZanTQ/YMi7fb+JMERqBFFS0zfLGmK1g9x0gN4P3NbnxOYCsL72XSyIyjv+M6ArcxZqese2qIWdbMna6IuMQT8jw9CT/xGBACUjHi2jxnrKQidID94eO3p0+wBwXzVusSBFOPXWYH+zBMgnLV7yB+hasmzbCW1S3E3cfmy79a0opaaYfgw0OLvJDYHh6iGJyT7pjfH2HB7UTOSW3iJhLJoMm3UCR1/RFz/QKN+UHWOtV9pMcpboLh+lQTlbGhvKSFzLU9t650HvToDlTV5ZaY8WFUkcnngu7RE+/fB6fHBW0/QKkGIae6UIVDOmwnpzOrTGYQQ+qLtoT2oIvVPgH4bcOHZKAnWp+HuNEn2ZI1ER+MhJd5tqVo1r+Etc0e9It/uU3tAiJM/mF6TtmZL9LUrcrit8GelVq8niOWr2gIqJKzdnN0J/60F5OF3TNutstclXDgPMOoOuIT1O8Egjr0mYYmLj1c5UfoVEdQ4P6ZbthS1SkoqVVSXkZ1yNDEgYM+7THfQwxrt0RFX+O64ReVXCP5suQqFhjNMfbY3g4CDGWPGMFWU10RWZXC/5FeuuiFR/82vmiuaV9AmLB68pVtQAxLuGtPopg0d0drFkL5Uj+CVk0Zk0ijrHYbp/hgiCi5KMD74bxjxE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
